import { useEffect, useState } from 'react'
import { useAuth } from '../auth/AuthContext'
import { Alert } from '../components/Alert'
import { AppShell } from '../components/AppShell'
import { StatusPill } from '../components/StatusPill'
import { ApiError, api } from '../lib/api'
import { formatDate, label, percentage } from '../lib/format'
import { navigate } from '../lib/route'
import type { ReviewDetail } from '../types'

export function ProfessionalReviewPage({ id }: { id: number }) {
  const { token } = useAuth(); const [review, setReview] = useState<ReviewDetail | null>(null); const [imageUrl, setImageUrl] = useState(''); const [fractureShown, setFractureShown] = useState<boolean | null>(null); const [comment, setComment] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { if (!token) return; api.professionalReview(id, token).then(r => { setReview(r); setFractureShown(r.agreesWithAi === undefined ? null : r.agreesWithAi === (r.predictedClass !== 'NO_FRACTURE')); setComment(r.comment ?? '') }).catch(e => setError(e instanceof ApiError ? e.message : 'Review could not be loaded.')); fetch(api.professionalReviewImageUrl(id), { headers: { Authorization: `Bearer ${token}` } }).then(r => r.ok ? r.blob() : Promise.reject()).then(blob => setImageUrl(URL.createObjectURL(blob))).catch(() => setError('The consented X-ray could not be loaded.')) }, [id, token])
  async function submit() { if (!token || fractureShown === null || !comment.trim() || !review) { setError('Choose Yes or No and enter professional comments.'); return }; setBusy(true); setError(''); try { const aiShowsFracture = review.predictedClass !== 'NO_FRACTURE'; setReview(await api.completeProfessionalReview(id, { agreesWithAi: fractureShown === aiShowsFracture, comment }, token)) } catch (e) { setError(e instanceof ApiError ? e.message : 'Review could not be completed.') } finally { setBusy(false) } }
  return <AppShell active="professional"><button className="text-button" onClick={() => navigate('/professional/reviews')}>← Back to reviews</button>{error && <Alert>{error}</Alert>}{!review ? <div className="loading-card">Loading review…</div> : <><section className="page-heading"><div><span className="eyebrow">Professional review</span><h1>{review.predictionReference}</h1><p>{review.originalFileName} · Uploaded {formatDate(review.createdAt)}</p></div><StatusPill value={review.riskCategory} /></section><section className="review-grid"><div className="image-preview">{imageUrl && <img src={imageUrl} alt="Consented X-ray" />}</div><div className="review-details"><div className="result-meta" style={{ borderLeft: 0, paddingLeft: 0 }}><div><span>AI prediction</span><strong>{label(review.predictedClass)}</strong></div><div><span>Confidence</span><strong>{percentage(review.confidence)}</strong></div><div><span>Model version</span><strong>{review.modelVersion}</strong></div></div>{review.explanation && <article className="ai-explanation-card"><h2>Groq explanation</h2><p>{review.explanation.summary}</p></article>}<h2>Does the X-ray show a fracture?</h2><div className="landing-actions"><button className={fractureShown === true ? 'primary-button' : 'secondary-button'} onClick={() => setFractureShown(true)}>Yes</button><button className={fractureShown === false ? 'primary-button' : 'secondary-button'} onClick={() => setFractureShown(false)}>No</button></div><label className="form-stack">Professional comments<textarea required maxLength={2000} rows={6} value={comment} onChange={e => setComment(e.target.value)} /></label>{review.status === 'PENDING' ? <button className="primary-button" disabled={busy} onClick={submit}>{busy ? 'Submitting…' : 'Submit review'}</button> : <div className="alert alert--success">This review was completed on {review.completedAt ? formatDate(review.completedAt) : 'the recorded date'}.</div>}</div></section></>}</AppShell>
}
